export const ADD_SERVICE = "ADD_SERVICE";
export const REMOVE_SERVICE = "REMOVE_SERVICE";
export const CHANGE_ADD_SERVICE_FIELD = "CHANGE_ADD_SERVICE_FIELD";
export const CHANGE_SERVICE = "CHANGE_SERVICE";
export const CHANGE_SERVICE_CANCEL = "CHANGE_SERVICE_CANCEL";

export const FETCH_SERVICES_REQUEST = "FETCH_SERVICES_REQUEST";
export const FETCH_SERVICES_FAILURE = "FETCH_SERVICES_FAILURE";
export const FETCH_SERVICES_SUCCESS = "FETCH_SERVICES_SUCCESS";
export const FETCH_SERVICES_END_LOADING = "FETCH_SERVICES_END_LOADING";

export const IS_LOADING_REQUEST = "IS_LOADING_REQUEST";
export const IS_LOADING_FAILURE = "IS_LOADING_FAILURE";
export const IS_LOADING_SUCCESS = "IS_LOADING_SUCCESS";

export const ADD_SERVICES_REQUEST = "ADD_SERVICES_REQUEST";
export const ADD_SERVICES_FAILURE = "ADD_SERVICES_FAILURE";
export const ADD_SERVICES_SUCCESS = "ADD_SERVICES_SUCCESS";

export const CHANGE_SERVICE_FIELD = "CHANGE_SERVICE_FIELD";
export const CHANGE_SERVICES_REQUEST = "CHANGE_SERVICES_REQUEST";
export const CHANGE_SERVICES_FAILURE = "CHANGE_SERVICES_FAILURE";
export const CHANGE_SERVICES_SUCCESS = "CHANGE_SERVICES_SUCCESS";
export const CHANGE_SERVICES_INIT = "CHANGE_SERVICES_INIT";
